<a href="https://colab.research.google.com/github/egipot/ZTMPy/blob/main/ZTM_ML_313_iris_data_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Import the data
  2. Clean the data (not needed in this case)

https://en.wikipedia.org/wiki/Iris_flower_data_set

https://www.kaggle.com/datasets/uciml/iris


In [1]:
from sklearn.datasets import load_iris
iris = load_iris()

In [2]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [3]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [4]:
# X = inputs
X = iris.data

# y = target / answer
y = iris.target

#f(X) = y

#columns = features
feature_names = iris.feature_names

target_names = iris.target_names

In [5]:
feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [6]:
target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

# 3. Splitting the data

In [7]:
type(X)

numpy.ndarray

In [8]:
#https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html
#train_test_split == split arrays or matrices into random train and test subsets.

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)



In [9]:
print(X_train.shape)

(120, 4)


In [10]:
print(X_test.shape)

(30, 4)


#4. Create a model

In [11]:
#https://scikit-learn.org/stable/modules/neighbors.html

from sklearn.neighbors import KNeighborsClassifier
import numpy as np

# Model 1:
knn = KNeighborsClassifier(n_neighbors=3)  #3 due to the 3 species of iris in the expected output
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)

#Accuracy = 0.9666666666666667

# 5. Check the output

In [12]:
from sklearn import metrics
print(f'Accuracy = {metrics.accuracy_score(y_test, y_pred)}')

Accuracy = 0.9666666666666667


In [13]:
# predict a sample

sample = [[3,5,4,2], [2,3,5,4]]
predictions = knn.predict(sample)
pred_species = [iris.target_names[p] for p in predictions]
print(f'predictions: {pred_species}')


predictions: ['versicolor', 'virginica']


Optional: K Nearest Neighbour
If you would like to learn more about K-Nearest Neighbours algorithm for classification, this interactive demo will help you understand the parameters that go into it, including the N value we experimented with in the previous video: http://vision.stanford.edu/teaching/cs231n-demos/knn/

To learn more about how this algorithm works, you can also check out this article: https://www.analyticsvidhya.com/blog/2018/08/k-nearest-neighbor-introduction-regression-python/

# 6. Improving the data

In [ ]:
# Use other algorithms in sklearn
# https://scikit-learn.org/stable/index.html

In [ ]:
#https://scikit-learn.org/stable/modules/neighbors.html#nearest-neighbors-classification
#Neighborhood Components Analysis
#Neighborhood Components Analysis (NCA, NeighborhoodComponentsAnalysis) is a distance metric learning algorithm
#which aims to improve the accuracy of nearest neighbors classification compared to the standard Euclidean distance.
#The algorithm directly maximizes a stochastic variant of the leave-one-out k-nearest neighbors (KNN) score on the training set.
#It can also learn a low-dimensional linear projection of data that can be used for data visualization and fast classification.


In [14]:
# Run again with test size = 0.7 but random_state changed from 45 to 0
# https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.NeighborhoodComponentsAnalysis.html#sklearn.neighbors.NeighborhoodComponentsAnalysis
# random_stateint, RandomState instance or None, default=None = Controls the shuffling applied to the data before applying the split. Pass an int for reproducible output across multiple function calls.

from sklearn.neighbors import (NeighborhoodComponentsAnalysis, KNeighborsClassifier)
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
X, y = load_iris(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, test_size=0.7, random_state=0)
nca = NeighborhoodComponentsAnalysis(random_state=0)
knn = KNeighborsClassifier(n_neighbors=3)
nca_pipe = Pipeline([('nca', nca), ('knn', knn)])
nca_pipe.fit(X_train, y_train)
print(nca_pipe.score(X_test, y_test))
#0.9904761904761905 - the best result

0.9904761904761905


In [22]:
sample = [[3,5,4,2], [2,3,5,4]]
predictions = knn.predict(sample)
pred_species = [iris.target_names[p] for p in predictions]
print('predictions: ', pred_species)

predictions:  ['versicolor', 'versicolor']


In [23]:
#
#store the model using the job lib module into a file (*.joblib) in order to have a model persistence

import joblib
model = joblib.dump(knn, 'mlbrain.joblib')

In [24]:
#assign the dumped/stored model

model = joblib.load('mlbrain.joblib')
model.predict(X_test)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [25]:
sample = [[3,5,4,2], [2,3,5,4]]
predictions = knn.predict(sample)
pred_species = [iris.target_names[p] for p in predictions]
print('predictions: ', pred_species)

predictions:  ['versicolor', 'versicolor']
